# Generated by Django 3.1.4 on 2022-02-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_news_newsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.news'),
        ),
    ]
