# Generated by Django 3.1.4 on 2022-02-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_subplan_subplanfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='highlight_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
