# Generated by Django 3.1.4 on 2022-02-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_subscriber_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='adress',
            field=models.TextField(),
        ),
    ]
