# Generated by Django 3.1.4 on 2022-02-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_notifuserstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifuserstatus',
            options={'verbose_name_plural': 'Notification Status'},
        ),
        migrations.RenameField(
            model_name='notify',
            old_name='notify_details',
            new_name='notify_detail',
        ),
    ]
