# Generated by Django 3.1.4 on 2022-03-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_subscription_reg_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name_plural': 'News Image'},
        ),
        migrations.AddField(
            model_name='trainer',
            name='Facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Twitter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
