# Generated by Django 3.1.4 on 2022-03-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220302_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAchivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('detail', models.TextField()),
                ('img', models.ImageField(upload_to='trainers_achivements/')),
            ],
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='Twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
