# Generated by Django 3.1.4 on 2022-03-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20220302_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerachivement',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trainer'),
        ),
        migrations.AlterField(
            model_name='trainerachivement',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trainerachivement',
            name='img',
            field=models.ImageField(null=True, upload_to='trainers_achivements/'),
        ),
        migrations.AlterField(
            model_name='trainerachivement',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
