# Generated by Django 3.1.4 on 2022-03-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_trainersalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerNotifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_msg', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='trainersalary',
            options={'verbose_name_plural': 'trainer salary'},
        ),
        migrations.AlterField(
            model_name='trainersalary',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
