# Generated by Django 3.1.4 on 2022-03-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_trainermsg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainermsg',
            options={'verbose_name_plural': 'messages to trainer'},
        ),
        migrations.AlterField(
            model_name='trainermsg',
            name='user_type',
            field=models.CharField(blank=True, default='admin', max_length=100),
        ),
    ]
