# Generated by Django 3.1.4 on 2022-03-29 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_trainertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainertask',
            name='task',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainertask',
            name='trainer_ts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_ts', to='main.trainer'),
        ),
    ]
