# Generated by Django 3.1.4 on 2022-03-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20220329_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainertask',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
