# Generated by Django 3.1.4 on 2022-03-30 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_remove_trainertask_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainertask',
            name='user_ts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_ts', to='main.assignsubscriber'),
        ),
    ]
