# Generated by Django 4.0.3 on 2022-04-19 16:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_alter_subscriber_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
