# Generated by Django 4.0.3 on 2022-04-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_alter_trainer_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerMsg',
        ),
    ]
