# Generated by Django 4.0.3 on 2022-04-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_delete_trainermsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='read_by_trainer',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='read_by_user',
        ),
    ]
