# Generated by Django 4.0.3 on 2022-06-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_remove_notify_read_by_trainer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name_plural': 'Gallery Image'},
        ),
    ]
